const money=v=>Number(v).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
let all=[],active="Todos",cart=JSON.parse(localStorage.getItem("nobreCart")||"{}");
const $=s=>document.querySelector(s);
async function init(){all=await fetch("produtos.json").then(r=>r.json());$("#productTotal").textContent=all.length;$("#categoryTotal").textContent=new Set(all.map(p=>p.categoria)).size;makeCategories();render();renderCart()}
function makeCategories(){const cats=["Todos",...new Set(all.map(p=>p.categoria))];$("#categories").innerHTML=cats.map(c=>`<button class="${c===active?"active":""}" data-cat="${c}">${c}</button>`).join("");document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{active=b.dataset.cat;makeCategories();render()})}
function filtered(){const q=$("#search").value.trim().toLowerCase();let a=all.filter(p=>(active==="Todos"||p.categoria===active)&&(`${p.nome} ${p.marca}`.toLowerCase().includes(q)));const s=$("#sort").value;if(s==="name")a.sort((x,y)=>x.nome.localeCompare(y.nome));if(s==="low")a.sort((x,y)=>x.preco-y.preco);if(s==="high")a.sort((x,y)=>y.preco-x.preco);return a}
function render(){const list=filtered();$("#products").innerHTML=list.map(p=>`<article class="card"><div class="image-wrap">${p.imagem?`<img src="${p.imagem}" alt="${p.nome}" loading="lazy">`:`<div class="placeholder"><img src="logo-nobre.png" alt=""><span>Imagem em breve</span></div>`}${p.destaque?'<span class="badge">DESTAQUE</span>':""}</div><div class="card-body"><span class="category">${p.categoria}</span><h3>${p.nome}</h3><div class="pack">${p.embalagem}</div><div class="price">${money(p.preco)}</div><div class="unit">${money(p.precoUnitario)} por unidade</div><button class="add" onclick="add(${p.id})">Adicionar ao pedido</button></div></article>`).join("")||"<p>Nenhum produto encontrado.</p>"}
function save(){localStorage.setItem("nobreCart",JSON.stringify(cart))}
function add(id){cart[id]=(cart[id]||0)+1;save();renderCart();openCart()}
function change(id,d){cart[id]=(cart[id]||0)+d;if(cart[id]<=0)delete cart[id];save();renderCart()}
function renderCart(){const entries=Object.entries(cart);let total=0,count=0;$("#cartItems").innerHTML=entries.map(([id,q])=>{const p=all.find(x=>x.id==id);if(!p)return"";total+=p.preco*q;count+=q;return `<div class="cart-item"><div><b>${p.nome}</b><small>${p.embalagem} • ${money(p.preco)}</small></div><div class="qty"><button onclick="change(${id},-1)">−</button><span>${q}</span><button onclick="change(${id},1)">+</button></div></div>`}).join("")||"<p>Seu pedido está vazio.</p>";$("#cartTotal").textContent=money(total);$("#cartCount").textContent=count}
function openCart(){$("#drawer").classList.add("open");$("#overlay").classList.add("show")}function closeCart(){$("#drawer").classList.remove("open");$("#overlay").classList.remove("show")}
$("#cartBtn").onclick=openCart;$("#closeCart").onclick=closeCart;$("#overlay").onclick=closeCart;$("#search").oninput=render;$("#sort").onchange=render;
$("#clearCart").onclick=()=>{cart={};save();renderCart()}
$("#sendOrder").onclick=()=>{const entries=Object.entries(cart);if(!entries.length)return alert("Adicione produtos ao pedido.");let total=0;const lines=entries.map(([id,q])=>{const p=all.find(x=>x.id==id);const sub=p.preco*q;total+=sub;return `• ${q}x ${p.nome} — ${p.embalagem} — ${money(sub)}`});const msg=`Olá, quero fazer este pedido na Nobre Distribuidora:\n\n${lines.join("\n")}\n\nTotal estimado: ${money(total)}\n\nFavor confirmar disponibilidade e condições de entrega.`;window.open(`https://wa.me/5598984772841?text=${encodeURIComponent(msg)}`,"_blank")}
init();