const C=window.CATALOGO_CONFIG;
let produtos=[],categoria="Todos",soFavoritos=false,carrinho=JSON.parse(localStorage.getItem("nobreCarrinho")||"{}");
let favoritos=JSON.parse(localStorage.getItem("nobreFavoritos")||"[]"),produtoAberto=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const moeda=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const sim=v=>String(v||"").trim().toLowerCase()==="sim";
const agora=()=>new Date();
function num(v){return Number(String(v??"").replace(/\./g,"").replace(",","."))||0}
function data(v){if(!v)return null;let d=new Date(v);return isNaN(d)?null:d}
function csv(text){let linhas=[],linha=[],campo="",asp=false;for(let i=0;i<text.length;i++){let c=text[i],n=text[i+1];if(c=='"'&&asp&&n=='"'){campo+='"';i++}else if(c=='"')asp=!asp;else if(c==','&&!asp){linha.push(campo);campo=""}else if((c=='\n'||c=='\r')&&!asp){if(c=='\r'&&n=='\n')i++;linha.push(campo);campo="";if(linha.some(x=>x!==""))linhas.push(linha);linha=[]}else campo+=c}if(campo||linha.length){linha.push(campo);linhas.push(linha)}let h=linhas.shift().map(x=>x.trim());return linhas.map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]??""])))}
function ofertaAtiva(p){if(!sim(p.oferta)||!num(p.preco_oferta_embalagem))return false;let ini=data(p.oferta_inicio),fim=data(p.oferta_fim),n=agora();return(!ini||n>=ini)&&(!fim||n<=fim)}
function precoEmb(p){return ofertaAtiva(p)?num(p.preco_oferta_embalagem):num(p.preco_normal_embalagem)}
function precoUn(p){return Math.round((precoEmb(p)/Math.max(1,num(p.unidades_por_embalagem)))*100)/100}
function codigo(i){return String(i+1).padStart(3,"0")}
function imagem(p){return p.foto_url||"https://placehold.co/600x600?text=Produto"}
function salvar(){localStorage.setItem("nobreCarrinho",JSON.stringify(carrinho));localStorage.setItem("nobreFavoritos",JSON.stringify(favoritos))}
async function carregar(){try{if(!C.planilhaCsvUrl)throw 0;let r=await fetch(C.planilhaCsvUrl,{cache:"no-store"});produtos=csv(await r.text())}catch(e){$("#avisoDemo").textContent="Versão de demonstração: ligue a Planilha Google no arquivo config.js.";produtos=csv(await(await fetch("produtos_exemplo.csv")).text())}
produtos=produtos.filter(p=>sim(p.disponivel)).sort((a,b)=>num(a.ordem)-num(b.ordem));categorias();render();carrinhoUI();restaurarCliente();setInterval(()=>{render();if(produtoAberto)abrirProduto(produtoAberto)},1000)}
function categorias(){let cats=["Todos","🔥 Ofertas","❤️ Favoritos",...new Set(produtos.map(p=>p.categoria).filter(Boolean))];$("#categorias").innerHTML=cats.map(c=>`<button class="categoria ${c==categoria?"ativa":""}" data-c="${c}">${c}</button>`).join("");$$(".categoria").forEach(b=>b.onclick=()=>{categoria=b.dataset.c;soFavoritos=categoria==="❤️ Favoritos";categorias();render()})}
function selos(p){return `${ofertaAtiva(p)?'<span class="selo">🔥 OFERTA</span>':""}${sim(p.novidade)?'<span class="selo novo">🆕 NOVIDADE</span>':""}${sim(p.mais_vendido)?'<span class="selo vendido">⭐ MAIS VENDIDO</span>':""}`}
function contagem(p){let fim=data(p.oferta_fim);if(!ofertaAtiva(p)||!fim)return"";let ms=fim-agora();if(ms<=0)return"";let d=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000);return`⏳ ${d?d+"d ":""}${String(h).padStart(2,"0")}h ${String(m).padStart(2,"0")}m ${String(s).padStart(2,"0")}s`}
function render(){let termo=$("#busca").value.toLowerCase();let lista=produtos.filter((p,i)=>{let okCat=categoria==="Todos"||categoria==="❤️ Favoritos"||categoria==="🔥 Ofertas"&&ofertaAtiva(p)||p.categoria===categoria;let fav=!soFavoritos||favoritos.includes(i);return okCat&&fav&&`${p.produto} ${p.categoria}`.toLowerCase().includes(termo)});$("#produtos").innerHTML=lista.map(p=>{let i=produtos.indexOf(p),fav=favoritos.includes(i);return `<article class="card"><div class="card-img"><img src="${imagem(p)}"><button class="favorito" onclick="favoritar(${i})">${fav?"❤️":"🤍"}</button><div class="selos">${selos(p)}</div></div><div class="card-body"><span class="codigo">Cód. ${codigo(i)}</span><h3>${p.produto}</h3><div class="emb">${p.embalagem} com ${p.unidades_por_embalagem} unidades</div>${ofertaAtiva(p)?`<div class="preco-antigo">${moeda(num(p.preco_normal_embalagem))}</div>`:""}<div class="preco">${moeda(precoEmb(p))}</div><div class="unitario">${moeda(precoUn(p))} por unidade</div><div class="contador">${contagem(p)}</div><div class="card-acoes"><button class="adicionar" onclick="abrirProduto(${i})">Comprar</button><button class="compartilhar" onclick="compartilhar(${i})">Compartilhar</button></div></div></article>`}).join("")||"<p>Nenhum produto encontrado.</p>"}
function favoritar(i){favoritos=favoritos.includes(i)?favoritos.filter(x=>x!==i):[...favoritos,i];salvar();render()}
function abrirProduto(i){produtoAberto=i;let p=produtos[i],rel=produtos.map((x,j)=>({x,j})).filter(o=>o.j!==i&&o.x.categoria===p.categoria).slice(0,4);$("#detalheProduto").innerHTML=`<img class="detalhe-img" src="${imagem(p)}"><div class="selos-inline">${selos(p)}</div><p class="codigo">Cód. ${codigo(i)}</p><h2>${p.produto}</h2><p>${p.embalagem} com ${p.unidades_por_embalagem} unidades</p><h3>${moeda(precoEmb(p))} — ${p.embalagem}</h3><p>${moeda(precoUn(p))} — unidade</p><p class="contador">${contagem(p)}</p><label>Comprar como<select id="tipoCompra"><option value="embalagem">${p.embalagem}</option><option value="unidade">Unidade</option></select></label><label>Quantidade<input id="qtdCompra" type="number" min="1" value="1"></label><button class="primario" style="width:100%;border:0;border-radius:12px;padding:13px" onclick="adicionar(${i})">Adicionar ao carrinho</button><h3>Você também pode precisar</h3><div class="relacionados">${rel.map(o=>`<div class="mini" onclick="abrirProduto(${o.j})"><b>${o.x.produto}</b><br>${moeda(precoEmb(o.x))}</div>`).join("")||"Sem sugestões."}</div>`;abrirModal("modalProduto")}
function limite(p,t){return t==="embalagem"?num(p.limite_embalagem):num(p.limite_unidade)}
function adicionar(i){let p=produtos[i],t=$("#tipoCompra")?.value||"embalagem",q=Math.max(1,num($("#qtdCompra")?.value||1)),k=`${i}|${t}`,lim=limite(p,t),atual=carrinho[k]?.q||0;if(lim&&atual+q>lim)return alert(`Limite máximo: ${lim} ${t==="embalagem"?p.embalagem:"unidades"}.`);carrinho[k]={i,t,q:atual+q};salvar();carrinhoUI();fecharModal("modalProduto");abrirModal("modalCarrinho")}
function subtotal(it){let p=produtos[it.i];return (it.t==="embalagem"?precoEmb(p):precoUn(p))*it.q}
function carrinhoUI(){let its=Object.entries(carrinho);$("#contadorCarrinho").textContent=its.reduce((s,[,x])=>s+x.q,0);let total=0;$("#itensCarrinho").innerHTML=its.map(([k,it])=>{let p=produtos[it.i];if(!p)return"";total+=subtotal(it);return `<div class="item"><div><b>${p.produto}</b><div class="tipo-linha">${it.t==="embalagem"?p.embalagem:"Unidade"} • ${moeda(it.t==="embalagem"?precoEmb(p):precoUn(p))}</div></div><div><div class="controles"><button onclick="mudar('${k}',-1)">−</button><input type="number" min="0" value="${it.q}" onchange="digitar('${k}',this.value)"><button onclick="mudar('${k}',1)">+</button></div><small>${moeda(subtotal(it))}</small></div></div>`}).join("")||"<p>Seu carrinho está vazio.</p>";$("#totalCarrinho").textContent=moeda(total)}
function mudar(k,d){let it=carrinho[k],p=produtos[it.i],lim=limite(p,it.t);let q=it.q+d;if(lim&&q>lim)return alert(`Limite máximo: ${lim}.`);if(q<=0)delete carrinho[k];else it.q=q;salvar();carrinhoUI()}
function digitar(k,v){let it=carrinho[k],p=produtos[it.i],q=Math.max(0,num(v)),lim=limite(p,it.t);if(lim&&q>lim){alert(`Limite máximo: ${lim}.`);q=lim}if(!q)delete carrinho[k];else it.q=q;salvar();carrinhoUI()}
function compartilhar(i){let p=produtos[i],url=location.href.split("#")[0]+`#produto-${i}`;let txt=`NOBRE DISTRIBUIDORA\n\nCód. ${codigo(i)} — ${p.produto}\n${p.embalagem} com ${p.unidades_por_embalagem} unidades\n${p.embalagem}: ${moeda(precoEmb(p))}\nUnidade: ${moeda(precoUn(p))}\n\n${url}`;window.open(`https://wa.me/?text=${encodeURIComponent(txt)}`,"_blank")}
function abrirModal(id){$("#"+id).classList.add("aberto")}function fecharModal(id){$("#"+id).classList.remove("aberto")}
$$("[data-fechar]").forEach(b=>b.onclick=()=>fecharModal(b.dataset.fechar));$$(".modal").forEach(m=>m.onclick=e=>{if(e.target===m)fecharModal(m.id)})
$("#btnCarrinho").onclick=()=>abrirModal("modalCarrinho");$("#btnFavoritos").onclick=()=>{categoria="❤️ Favoritos";soFavoritos=true;categorias();render()}
$("#btnRepetir").onclick=()=>{let ult=JSON.parse(localStorage.getItem("nobreUltimoPedido")||"null");if(!ult)return alert("Ainda não há pedido anterior salvo.");carrinho=ult;salvar();carrinhoUI();abrirModal("modalCarrinho")}
$("#limparCarrinho").onclick=()=>{carrinho={};salvar();carrinhoUI()}
$("#irCheckout").onclick=()=>{if(!Object.keys(carrinho).length)return alert("Adicione produtos.");fecharModal("modalCarrinho");abrirModal("modalCheckout")}
$("#tipoRecebimento").onchange=()=>$("#camposEntrega").style.display=$("#tipoRecebimento").value==="Entrega"?"block":"none";
$("#busca").oninput=render;
function cliente(){return {nome:$("#clienteNome").value,cidade:$("#clienteCidade").value,pagamento:$("#pagamento").value,tipo:$("#tipoRecebimento").value,endereco:$("#endereco").value,referencia:$("#referencia").value,vendedor:$("#vendedor").value,obs:$("#observacoes").value}}
function restaurarCliente(){let d=JSON.parse(localStorage.getItem("nobreCliente")||"{}");$("#clienteNome").value=d.nome||"";$("#clienteCidade").value=d.cidade||"";$("#tipoRecebimento").value=d.tipo||"Entrega";$("#endereco").value=d.endereco||"";$("#referencia").value=d.referencia||"";$("#vendedor").value=d.vendedor||C.vendedorPadrao;$("#camposEntrega").style.display=$("#tipoRecebimento").value==="Entrega"?"block":"none"}
function resumoTexto(){let d=cliente(),total=0,linhas=Object.values(carrinho).map(it=>{let p=produtos[it.i],sub=subtotal(it);total+=sub;return `• ${it.q} ${it.t==="embalagem"?p.embalagem+"(s)":"unidade(s)"} — Cód. ${codigo(it.i)} ${p.produto} — ${moeda(sub)}`});return {d,total,linhas,texto:`${C.mensagemInicial}\n\nCliente/comércio: ${d.nome}\nCidade/povoado: ${d.cidade}\nPagamento: ${d.pagamento}\nRecebimento: ${d.tipo}${d.tipo==="Entrega"?`\nEndereço: ${d.endereco}\nReferência: ${d.referencia}`:""}\nVendedor: ${d.vendedor}\n\n${linhas.join("\n")}\n\nTotal: ${moeda(total)}${d.obs?`\n\nObservações: ${d.obs}`:""}\n\n${C.aviso}`}}
$("#revisarPedido").onclick=()=>{let r=resumoTexto();if(!r.d.nome||!r.d.cidade)return alert("Preencha nome e cidade/povoado.");localStorage.setItem("nobreCliente",JSON.stringify(r.d));$("#resumoPedido").innerHTML=`<p><b>Cliente:</b> ${r.d.nome}</p><p><b>Local:</b> ${r.d.cidade}</p><p><b>Pagamento:</b> ${r.d.pagamento}</p><p><b>Recebimento:</b> ${r.d.tipo}</p><hr>${r.linhas.map(x=>`<p>${x}</p>`).join("")}<hr><h3>Total: ${moeda(r.total)}</h3><p class="aviso">${C.aviso}</p>`;fecharModal("modalCheckout");abrirModal("modalRevisao")}
$("#enviarWhatsApp").onclick=()=>{let r=resumoTexto();localStorage.setItem("nobreUltimoPedido",JSON.stringify(carrinho));window.open(`https://wa.me/${C.whatsapp}?text=${encodeURIComponent(r.texto)}`,"_blank")}
window.addEventListener("load",()=>{let m=location.hash.match(/produto-(\d+)/);if(m)setTimeout(()=>abrirProduto(Number(m[1])),500)});carregar();
